name: mecha_app
description: "Mecha es una aplicación para estudiantes universitarios que transforma tus notas de clase en tesoros históricos. Gestiona y organiza tus notas por materia y fecha, comparte tus apuntes con compañeros y realiza un seguimiento de tu progreso académico. Creada para ser ejecuta en Android"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  ffi: ^2.1.2
  animate_do: 2.1.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mecha-logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/mecha-logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/mecha-logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/mecha-logo.jpg"

flutter:

 
  uses-material-design: true

  assets:
    - assets/
  