name: mecha_app
description: "Mecha es una aplicación para estudiantes universitarios que transforma tus notas de clase en tesoros históricos. Gestiona y organiza tus notas por materia y fecha, comparte tus apuntes con compañeros y realiza un seguimiento de tu progreso académico. Creada para ser ejecuta en Android"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true

  
  assets:
    - assets/
  